services:
  frontend:
    image: 738250824273.dkr.ecr.us-east-1.amazonaws.com/appfrontend:latest
    container_name: frontend-container
    ports:
      - "3000:3000"

  backend:
    image: 738250824273.dkr.ecr.us-east-1.amazonaws.com/appbackend:latest
    container_name: backend-container
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mydb123456
      MYSQL_DATABASE: food_db
      
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  my-db:
